### ISSUE TITLE
Call to undefined function Cvsouth\Entities\str_ends() 

### ISSUE THREAD

**Issue by jsamr** [cvsouth/entities#14]
Hi there! This is bug is due to the file `src/functions.php` not being autoloaded.
In addition, instead of polluting global namespace, I suggest adding your namespace in the `functions.php` file.
See my PR!

**Comment by cvsouth** [comment]
Hi Jules. I have `src/functions.php` included in the ServiceProvider::register method: https://github.com/cvsouth/entities/blob/master/src/Providers/ServiceProvider.php#L17. I'm wondering what configuration you are using for it not to pick this up? Not Laravel? Either way I'm happy for it to be included through `composer.json` if this is an issue for you an others. I'll accept the pull request and remove the line from ServiceProvider::register.

**Comment by jsamr** [comment]
@cvsouth Hi ! You are right, I am using Lumen! I thought that would not make any difference but it seems it does. Thanks a lot for your help :-)
