### ISSUE TITLE
Endless recursion due to empty top_class

### ISSUE THREAD

**Issue by mamedia-edv** [cvsouth/entities#20]
Hey there!

I'm currently facing an issue with your module:

I have one base model that inherits from your Entity model and one that inherits from my base model:
![image](https://user-images.githubusercontent.com/20066237/61875904-ebe96580-aeeb-11e9-833a-82811a94ce2c.png)

![image](https://user-images.githubusercontent.com/20066237/61875846-d07e5a80-aeeb-11e9-9dc4-dd01bc191b7c.png)

When I'm trying to execute the following query with data in the database I end up having a endless recursion (without the entry in the db I get an exception as expected) :

`$course = Course::where('scrape_id', '=', $entity['scrape_id'])->firstOrFail();`

I tried to debug the issue and it appears to me that the recursion happens because the function GetWithEntityID uses the first method which again ends up calling the get method of your EntityBuilder and calls again GetWithEntityID:
<img width="907" alt="Bildschirmfoto 2019-07-25 um 14 49 51" src="https://user-images.githubusercontent.com/20066237/61876190-9a8da600-aeec-11e9-8390-dc45d37e2f17.png">

Here is the call stack to visualize the recursion:
![image](https://user-images.githubusercontent.com/20066237/61876787-f1e04600-aeed-11e9-9c68-4377ce299408.png)

I'm running php 7.2 und laravel 5.8.29.

Andreas

**Comment by cvsouth** [comment]
Hi Andreas,

I'll try to get this sorted for you today.

Colin

**Comment by cvsouth** [comment]
I created your models as per the above and ran your query but was unable to recreate the error. 

Could I see the migrations? Also, while you are debugging, what are the values of `$current_class` and `$top_class` during the recursion?

**Comment by mamedia-edv** [comment]
Hi Colin,

thanks for your efforts!
Here is a quick overview over the variables in the ElevateMultiple function while debugging:

1st iteration:
<img width="1164" alt="Bildschirmfoto 2019-08-01 um 09 47 18" src="https://user-images.githubusercontent.com/20066237/62275242-d58a5f00-b441-11e9-9fb8-7cfeaa9f936a.png">

2nd iteration:
<img width="1164" alt="Bildschirmfoto 2019-08-01 um 09 47 24" src="https://user-images.githubusercontent.com/20066237/62275265-dfac5d80-b441-11e9-9bb7-e35c6c3436a7.png">

3rd iteration:
<img width="1164" alt="Bildschirmfoto 2019-08-01 um 09 47 37" src="https://user-images.githubusercontent.com/20066237/62275298-f05cd380-b441-11e9-8e23-05a331c02f5d.png">

4th iteration:
<img width="1164" alt="Bildschirmfoto 2019-08-01 um 09 47 44" src="https://user-images.githubusercontent.com/20066237/62275315-fb176880-b441-11e9-8abf-824feaa5dccb.png">

5th iteration:
<img width="1164" alt="Bildschirmfoto 2019-08-01 um 09 47 49" src="https://user-images.githubusercontent.com/20066237/62275336-036fa380-b442-11e9-965b-5d8e3855f373.png">
 
and so on...

Here are my migrations:
![image](https://user-images.githubusercontent.com/20066237/62275440-40d43100-b442-11e9-81b5-a81651bed7a5.png)
![image](https://user-images.githubusercontent.com/20066237/62275453-4b8ec600-b442-11e9-80cf-28146cfa04b5.png)

**Comment by cvsouth** [comment]
It's because of `$top_class` being `null`. Question is why. If you go into your database and open up the `entities` table, is `top_class` column populated for all the rows?

**Comment by mamedia-edv** [comment]
Yep, the `top_class` column is populated.
Here is what is currently in the database (test data):

entities table:
![image](https://user-images.githubusercontent.com/20066237/62276064-86452e00-b443-11e9-8872-f0c8d549790d.png)

scrape_entities table:
![image](https://user-images.githubusercontent.com/20066237/62276146-affe5500-b443-11e9-8e44-b899706427ab.png)

courses table:
![image](https://user-images.githubusercontent.com/20066237/62276188-c73d4280-b443-11e9-97c9-9e097bcc8129.png)

I'm a bit confused by the entities 1 to 4 - are there supposed to be rows with 'Cvsouth\Entities\EntityType' as `top_class`?

**Comment by cvsouth** [comment]
The database looks correct. I'm not sure why `$entity->top_class` is returning `null` as it is simply an attribute like any other and I've been unable to recreate this issue. Any chance I can access the project to take a look at what is going on?

```I'm a bit confused by the entities 1 to 4 - are there supposed to be rows with 'Cvsouth\Entities\EntityType' as top_class?```

That is normal. The different entity types you have registered (during migrations) are stored as entities themselves. Check `entity_types` table and you should see four rows, `Cvsouth\Entities\Entity`, `Cvsouth\Entities\EntityType`, `App\ScrapeEntity`, `App\Course`.

**Comment by mamedia-edv** [comment]
Sure, I'd love to give you access to the project in order to solve this issue. However I don't have it on github but on my own Go git service instance. I temporarily made the project public so you can clone it:
https://git.mamedia-edv.de/Andreas/MitFamilie-Crawler

After you have installed the project via composer and ran the migrations you should be able to run `php artisan db:seed` in order for you to insert dummy data. Check out the routes and you'll see that there is only one test route. If you open that route in the browser it will scrape some data from a website and insert a new Add\Course entity in the db. So far so good. 
If you run it a second time the issue occurs. Take a look at the SiteAdapter class. There you'll find the line where the query happens in line 87.

Keep in mind that this project is still under heavy development so it is a bit messy :)

**Comment by cvsouth** [comment]
Ok everything is installed and I've got to the error. I have to go out now but will debug later and figure out what is going wrong. You can make the project private again now if you want.

**Comment by cvsouth** [comment]
Should work now. Run `composer update cvsouth/entities` to get the latest release. Make sure you get version `5.8.2`. Let me know if that fixes it?

Also worth saying that the next few lines where you compare `->toJson()` outputs won't work at the moment because one of them will have the database auto-generated `id` etc and the new one will not. You could use `$hidden` on the entity to specific certain fields not to output, that might work, or compare the specific fields such as `if($course->title !== $newCourse->title || $course->description !== $newCourse->description || etc...)` which is probably what I would do in this case.

**Comment by mamedia-edv** [comment]
Awesome, It works now! Thank you very much.

Yep, I was expecting that comparing the output of `->toJson()` is probably not going to work right away but then I got stuck with the recursion issue :D But thank you for your advice!
