### ISSUE TITLE
Where clause on wrong table when querying foreign key

### ISSUE THREAD

**Issue by mamedia-edv** [cvsouth/entities#21]
Hey there!

I presumably found another bug in your code. I took your simple example from the github readme to demonstrate the issue. The only thing I added is a owner class and a foreign key in the animals table. The models have beed adapted accordingly:

Animal class:
![image](https://user-images.githubusercontent.com/20066237/63601990-d3419d80-c5c6-11e9-8940-6fe16a843cb6.png)

Bird class:
![image](https://user-images.githubusercontent.com/20066237/63602038-e3f21380-c5c6-11e9-9f55-845772cacc01.png)

Owner class:
![image](https://user-images.githubusercontent.com/20066237/63602062-f2402f80-c5c6-11e9-811a-206242a4505b.png)

Animals table migration:
![image](https://user-images.githubusercontent.com/20066237/63602131-0e43d100-c5c7-11e9-987c-c26777e1fced.png)

Birds table migration:
![image](https://user-images.githubusercontent.com/20066237/63602163-1b60c000-c5c7-11e9-92c8-080241f2a72d.png)

Owners table migration:
![image](https://user-images.githubusercontent.com/20066237/63602207-316e8080-c5c7-11e9-91c0-5f5ac57659d4.png)

When I'm trying to run the following demo code I get a sql error `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'owner_id' in 'where clause' (SQL: select * from `birds` where `owner_id` = 10)`

![image](https://user-images.githubusercontent.com/20066237/63602422-b063b900-c5c7-11e9-87e2-d81409d565f6.png)

Seems like the application is looking for the column in the wrong table - it there any way to solve that?

For debugging I provided the demo application here:
[cvsouth-test.zip](https://github.com/cvsouth/entities/files/3535067/cvsouth-test.zip)

Any help is appreciated!

Andreas

**Comment by mamedia-edv** [comment]
Alright, maybe I was too hasty...figured it out myself.
Apparently your module only checks for fillable fields but doesn't prefix things like foreign keys which are not in the fillable array.

See line 72 of the EntityQueryBuilder:
![image](https://user-images.githubusercontent.com/20066237/63604135-5b29a680-c5cb-11e9-8f3c-a38c13ac0483.png)

I fixed it by adding the owner_id to the fillable array **and clearing the cache afterwards**.
Might be a good idea to add this to the docs or even add compatibility to foreign keys.

**Comment by cvsouth** [comment]
Hi again.

Thanks for the feedback. As things are now, all database fields must be explicitly defined in the `$fillable` or `$guarded` array. It doesn't automatically detect foreign key field for example. 

It's a good suggestion though and I could make it detect foreign key fields so they don't have to be explicitly defined in $fillable. However it makes me think about the $fillable array more generally. 

I think perhaps it is not the best solution to have it use $fillable for determining the parent database fields as this puts constraints on how $fillable should be used (as you have found out) meaning it's usage then differs from base Eloquent.

I think instead it might be possible to look directly at the database and determine the fields at each level of inheritance and store an additional array under the hood for this functionality. It is cached (as you also found out) so performance is not really a problem and that way `$fillable` and `$guarded` can be used as per normal Eloquent.

**Comment by cvsouth** [comment]
Hi,

I have made some changes that should fix this and while I was at it made some additional changes including removing EntityType completely (makes migrations simpler) and some significant performance optimisations. For a while I've been meaning to rename the repo to something more descriptive and decided this would be a good moment. I actually created it as a new repo so I can leave this one for anyone using it and not break their composer update. I'll leave a note on the README of this repo that it is depreciated to a link to the new one which is https://github.com/cvsouth/eloquent-inheritance. I recommend moving to the new version.

There are a few changes to switch to nothing that time consuming:

- Replace `cvsouth/entities` with `cvsouth/eloquent-inheritance` and composer update. Versioning can stay the same (`5.8.*` i.e. consistent with the version of Laravel it is targeting).
- Replace `entity_id` with `common_id` in all files.
- Remove the insert and delete `EntityType` row from your migrations.
- Replace `Cvsouth\Entities\Entity` with `Cvsouth\EloquentInheritance\InheritableModel` as your base model
- Run `php artisan migrate:fresh`

If you can't run migrate:fresh for example if the code is running in production then let me know and I will put together a migration that will modify the database in place (renaming `entity_id` columns to `common_id` and `entities` table to `base_models`).

Let me know if there are any problem.

**Comment by mamedia-edv** [comment]
Hi!
Have you already published your new repo to packagist.org?
Because I've no luck switching to the new cvsouth/eloquent-inheritance.

Andreas

**Comment by cvsouth** [comment]
Does it work now?

**Comment by mamedia-edv** [comment]
Hi!

I was now able to switch to the new repo.
However I think instead of `common_id ` as you said in one of your previous replies it should be `base_id ` as shown in the repo readme.

Unfortunately I now get another exception. I changed the demo application from my previous post as explained by you and now I get the following exception:
![image](https://user-images.githubusercontent.com/20066237/65152854-0c83f680-da29-11e9-9fd7-f97994de3f87.png)

Andreas

**Comment by cvsouth** [comment]
Hi,

You're right about it being `base_id`, I changed that from `common_id` at the last minute, but forgot to come here and update my response, apologies.

As for the bug, try doing `composer update cvsouth/eloquent-inheritance` ensuring that you get version `1.0.1`, and see if that fixes it.

Colin
