### ISSUE TITLE
Call to undefined function Cvsouth\Entities\str_ends()

### ISSUE THREAD

**Issue by angelformica** [cvsouth/entities#5]
Hello, thank you for sharing, this is great!

I am getting this exception when rolling back a migration.

  at /home/vagrant/Code/transfers-usa/vendor/cvsouth/entities/src/EntityQueryBuilder.php:43

  > 43|         if($column === "*" || str_ends($column, ".*")) return $column;
    44| 
    45|         // already prefixed?
    46|         if(instr(".", $column)) return $column;
    47| 

Shouldn't that be str_finish()?

Best regards

**Comment by cvsouth** [comment]
This function comes from another package, I didn't realise it was used here without a dependency. I pulled the function into this package so if you update it should work now.

And thanks for the feedback!

**Comment by angelformica** [comment]
Excellent! thanks!
