### ISSUE TITLE
Levels of inheritance

### ISSUE THREAD

**Issue by angelformica** [cvsouth/entities#9]
Hello again,

I am trying to achieve this:

Items->Services->Extras

But it keeps throwing me SQL errors.

If I do it only with Items->Services then it works.

Is it possible to have more levels of inheritance, and if it is, how can I do this?

Thank you!

**Comment by cvsouth** [comment]
You should be able to have any number of levels of inheritance. I need to see the code to be able to comment specifically. If you add me as a contributor temporarily I will take a look for you, or send your your migrations and model classes to colin@riseresolution.com.

**Comment by cvsouth** [comment]
> The owner of this repository (xca-it) is already at their plan limit and will need to upgrade before adding more users.

**Comment by cvsouth** [comment]
> The owner of this repository is already at their plan limit and will need to upgrade before adding more users.

**Comment by angelformica** [comment]
Sorry, You should be able to get in now.

**Comment by cvsouth** [comment]
Can you show me an example of the error? Is it anything to do with the `created_at` and `updated_at` columns by any chance?

**Comment by angelformica** [comment]
No, this is the error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list' (SQL: insert into `services` (`name`, `description`, `entity_id`) values (Go Pro, Go Pro Description, 26))

**Comment by angelformica** [comment]
name and description are fields in the parent table items. extras extends services, services extends items, items extends entity

**Comment by cvsouth** [comment]
Try putting an empty `$fillable` into the Services model like so:
> class Service extends Item
{
  public $table = "services";
  protected $fillable = [ ];
}

**Comment by cvsouth** [comment]
If that works I will update the package so you don't need the empty `$fillable` in future but just so we know if that is the problem?

**Comment by angelformica** [comment]
Yeahh! that worked!!!!  Awesome, Thank you!

**Comment by cvsouth** [comment]
No problem at all.

Thanks for helping make the package better!
